### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by zbluhm** [rxlabz/flutter_video_launcher#3]
Hi, recently tried to implement your plugin in my app and after falling all the installation instructions (adding to pubspec, running packages get, running flutter upgrade, importing, etc) I'm getting the following error when trying to launch a video:

`E/flutter (22599): MissingPluginException(No implementation found for method canLaunchVideo on channel bz.rxla.flutter/video_launcher)
E/flutter (22599): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:153:7)
E/flutter (22599): <asynchronous suspension>
E/flutter (22599): #1      canLaunchVideo (package:video_launcher/video_launcher.dart:24:25)
E/flutter (22599): <asynchronous suspension>
E/flutter (22599): #2      SalesDayHomeState._launchVideo (/data/user/0/com.yourcompany.salesdaydemo/cache/salesday_demo1aL9KB/salesday_demo/lib/salesday_home.dart:157:15)
E/flutter (22599): <asynchronous suspension>
E/flutter (22599): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:296:14)
E/flutter (22599): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:71:24)
E/flutter (22599): #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:149:9)
E/flutter (22599): #6      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:119:7)
E/flutter (22599): #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:119:27)
E/flutter (22599): #8      BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:131:20)
E/flutter (22599): #9      BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:105:22)
E/flutter (22599): #10     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (22599): #11     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:45:7)
E/flutter (22599): #12     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:38:5)
E/flutter (22599): #13     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:55)`

Please let me know if there is any other info I can provide.

Thanks!

**Comment by rxlabz** [comment]
Hi, is it on Android or iOS ?

**Comment by zbluhm** [comment]
Sorry I should have specified - It's on Android.

**Comment by rxlabz** [comment]
did you `flutter build apk` ?

**Comment by zbluhm** [comment]
That seemed to fix the issue, thanks!

**Comment by rxlabz** [comment]
I probably need to add this to the readme, but as it's not in official docs... I'm not sure in which cases it's needed 🤔...
Not related : if the plugin works and is useful to you, please consider to ⭐️ it ;)

**Comment by zbluhm** [comment]
Thanks, the plugin is quite useful!

One quick question: Where is it best to store the local video file? When adding it as an asset to the pubspec file and referencing its location with your plugin the video does not appear to be found.

**Comment by rxlabz** [comment]
Hi, to use the plugin you must know the path of the file : remote or local. There is no easy way to find the assets path, so you can't play it directly from the assets bundle... but, you can copy your video file from the assetBundle to the appStorageDirectory ( cf package/path_provider ). Then you normally can play it. Same question was asked for the audio player https://github.com/rxlabz/audioplayer/issues/5

**Comment by zbluhm** [comment]
Hey, thanks for the response.

I did exactly as was outlined and am still struggling to get the video to play.

I call the following code on app load:
`  Future<Null> copyVideo () async {
    final dir = await getApplicationDocumentsDirectory();
    final file = new File("${dir.path}/property_video.mp4");
    if(!(await file.exists())) {
      final videoData = await rootBundle.load("videos/property_video.mp4");
      print(videoData.lengthInBytes);
      final bytes = videoData.buffer.asUint8List();
      file.writeAsBytes(bytes, flush: true);
    }
  }`

The print statement shows the correct amount of bytes, so I know the video is correctly being copied.

And then the following on a button press to launch the video:
`  Future<Null> _launchVideo() async {
    final dir = await getApplicationDocumentsDirectory();
    final file = new File("${dir.path}/property_video.mp4");
    print(file.uri.path);
    if (await canLaunchVideo(file.uri.path, isLocal:true)) {
      await launchVideo(file.uri.path, isLocal:true);
    } else {
      throw 'Could not launch ${file.uri.path}';
    }
  }`

Anything glaringly obvious that I might be doing wrong?

**Comment by rxlabz** [comment]
Hi,
I updated the plugin example to play a video asset, based on your example, and it works for me. can you please try it ? https://github.com/rxlabz/flutter_video_launcher/tree/master/example

**Comment by zbluhm** [comment]
Thanks for the updated example, however this error is being thrown upon video launch:
`
E/flutter (20420): [ERROR:lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (20420): Could not launch /data/user/0/com.yourcompany.salesdaydemo/app_flutter/property_video.mp4
E/flutter (20420): #0      SalesDayHomeState._launchVideo (/data/user/0/com.yourcompany.salesdaydemo/cache/salesday_demoDIAqxf/salesday_demo/lib/salesday_home.dart:210:8)
E/flutter (20420): <asynchronous suspension>
E/flutter (20420): #1      SalesDayHomeState._launchLocalAsset.<anonymous closure> (/data/user/0/com.yourcompany.salesdaydemo/cache/salesday_demoDIAqxf/salesday_demo/lib/salesday_home.dart:201:22)
E/flutter (20420): #2      State.setState (package:flutter/src/widgets/framework.dart:1056:30)
E/flutter (20420): #3      SalesDayHomeState._launchLocalAsset (/data/user/0/com.yourcompany.salesdaydemo/cache/salesday_demoDIAqxf/salesday_demo/lib/salesday_home.dart:201:7)
E/flutter (20420): #4      SalesDayHomeState.copyLocalAsset.<anonymous closure> (/data/user/0/com.yourcompany.salesdaydemo/cache/salesday_demoDIAqxf/salesday_demo/lib/salesday_home.dart:196:7)
E/flutter (20420): #5      State.setState (package:flutter/src/widgets/framework.dart:1056:30)
E/flutter (20420): #6      SalesDayHomeState.copyLocalAsset (/data/user/0/com.yourcompany.salesdaydemo/cache/salesday_demoDIAqxf/salesday_demo/lib/salesday_home.dart:194:5)
E/flutter (20420): <asynchronous suspension>
E/flutter (20420): #7      SalesDayHomeState._loadOrLaunchLocalAsset (/data/user/0/com.yourcompany.salesdaydemo/cache/salesday_demoDIAqxf/salesday_demo/lib/salesday_home.dart:186:55)
E/flutter (20420): #8      SalesDayHomeState.build.buildButtonColumn.<anonymous closure> (/data/user/0/com.yourcompany.salesdaydemo/cache/salesday_demoDIAqxf/salesday_demo/lib/salesday_home.dart:50:19)
E/flutter (20420): #9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:296:14)
E/flutter (20420): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:71:24)
E/flutter (20420): #11     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:149:9)
E/flutter (20420): #12     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:119:7)
E/flutter (20420): #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:119:27)
E/flutter (20420): #14     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:131:20)
E/flutter (20420): #15     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:105:22)
E/flutter (20420): #16     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (20420): #17     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:45:7)
E/flutter (20420): #18     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:38:5)
E/flutter (20420): #19     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:55)
`
Thanks!

**Comment by rxlabz** [comment]
🤔...
do you run on device or simulator ?
does my example work on it ? 
does your video file work if played remotely ?

**Comment by zbluhm** [comment]
I test on a device (Galaxy S8) and use your code verbatim to launch the video. The video file works if I download it to my device and select it in a player (such as google photos).
